pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="/Users/manatsawisutlaeo/Desktop/Repositories/palo-it-training/devops-onboarding/testing-strategy-3"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        E2E_PATH = "${PROJECT_PATH}/e2e-web"
        WEB_PATH = "${PROJECT_PATH}/web"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
    }

    stages {
        stage('Build') {
           steps {
                dir("${SCRIPTS_PATH}") {
                    sh "echo building..."
                }
                sh "echo $(pwd)"
            }
        }
        stage('Test environment DEV') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Test"
                    """
                }
            }
        }
        stage('Deployment') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Deployment"
                    """
                }
            }
        }
    }
}