pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="${env.JENKINS_HOME}/workspace/OnBoardingPart3/testing-strategy-3"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        E2E_PATH="/Users/manatsawisutlaeo/Desktop/Repositories/palo-it-training/devops-onboarding/testing-strategy-3/e2e-web"
        WEB_PATH="/Users/manatsawisutlaeo/Desktop/Repositories/palo-it-training/devops-onboarding/testing-strategy-3/web"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
    }

    stages {
        stage('Build') {
           steps {
                dir("${WEB_PATH}") {
                    sh "echo building..."
                    sh "npm i"
                    sh "npm run start &"
                }
            }
        }
        stage('Test environment DEV') {
            steps {
                dir("${E2E_PATH}") {
                   sh "echo testing..."
                   sh "npm i"
                   sh "npm run test"
                }
            }
        }
        stage('Deployment') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Deployment"
                    """
                }
            }
        }
    }
}